[package]
name = "merkle"
version = "0.1.0"
edition = "2021"
authors = ["Keith Noguchi <hack@noguchi.us>"]

[dependencies]
generic-array = "0.14"
digest = "0.10"

[dev-dependencies]
crossbeam = "0.8"
sha3 = "0.10"
hex-literal = "0.3"
